### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array(4)
print(a)

4


In [ ]:
# 2D(collection of 1D objects)
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D(collection of 2D objects)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 4D(collection of 3D objects)
d = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(d)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
# np.array().reshape(a,b,c)
# a → number of blocks (or layers)

# b → number of rows in each block

# c → number of columns in each row

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.seed(21)
np.random.random((3,4))

array([[0.04872488, 0.28910966, 0.72096635, 0.02161625],
       [0.20592277, 0.05077326, 0.30227189, 0.66391029],
       [0.30811439, 0.58359128, 0.06957095, 0.86740448]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print('a1=',a1, '\n')
print('a2=',a2)

a1= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

a2= [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operations

# arithmetic
print('a1 +2=',a1+2,'\n')

print('a1 ** 2=',a1 ** 2,'\n')

a1 +2= [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]] 

a1 ** 2= [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 



In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
print('a1=a2=',a1+a2,'\n')
print('a1-a2=',a1-a2,'\n')
print('a1*a2=',a1*a2,'\n')
print('a1/a2=',a1/a2,'\n')


a1=a2= [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

a1-a2= [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]] 

a1*a2= [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

a1/a2= [[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 



### Array Functions

In [ ]:
np.random.seed(123)
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[70., 29., 23.],
       [55., 72., 42.],
       [98., 68., 48.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(np.max(a1,axis=1))
print(np.min(a1,axis=1))
print(np.sum(a1))
print(np.prod(a1))

[70. 72. 98.]
[23. 42. 48.]
505.0
2483959874457600.0


In [ ]:
# mean/median/std/var
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))

[40.66666667 56.33333333 71.33333333]
[29. 55. 68.]
[20.8859336  12.28368385 20.54804668]
[436.22222222 150.88888889 422.22222222]


In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
# dot product of matrices is calculated for nxm and mxq dimensional matirces.
#A (2×3)              B (3×2)

# [ 1   2   3 ]   ×   [ 7    8  ]
# [ 4   5   6 ]       [ 9   10  ]
#                     [ 11   12 ]

# C (2×2)

# [ (1×7 + 2×9 + 3×11)    (1×8 + 2×10 + 3×12) ]
# [ (4×7 + 5×9 + 6×11)    (4×8 + 5×10 + 6×12) ]

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
print(np.log(a1),'\n')
print(np.exp(a1))

[[4.24849524 3.36729583 3.13549422]
 [4.00733319 4.27666612 3.73766962]
 [4.58496748 4.21950771 3.87120101]] 

[[2.51543867e+30 3.93133430e+12 9.74480345e+09]
 [7.69478527e+23 1.85867175e+31 1.73927494e+18]
 [3.63797095e+42 3.40427605e+29 7.01673591e+20]]


In [ ]:
# round/floor/ceil
np.random.seed(123)
print(np.round(np.random.random((2,3))*100),'\n')
print(np.floor(np.random.random((2,3))*100),'\n')
print(np.ceil(np.random.random((2,3))*100))

[[70. 29. 23.]
 [55. 72. 42.]] 

[[98. 68. 48.]
 [39. 34. 72.]] 

[[44.  6. 40.]
 [74. 19. 18.]]


### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print('a1=',a1,'\n')
print('a2=',a2,'\n')
print('a3=',a3)

a1= [0 1 2 3 4 5 6 7 8 9] 

a2= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

a3= [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(a1[7])

7


In [ ]:
print(a1[0:10:2])

[0 2 4 6 8]


In [ ]:
print(a1[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a2[1,0]) # to fetch 2nd row and 1st column

4


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a3[1,0,1]) # a3[1->2nd block, 0->1st row,1->2nd column]

5


In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:] # to fetch the 1st row and all the columns

array([0, 1, 2, 3])

In [ ]:
a2[:,2] # to fetch the 3rd column

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3] # to fetch 2nd and 3rd row and 2nd and 3rd column

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,1::2] # to fetch 2nd and 4th column and 1st and 3rd row

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[1] # to fetch the 2nd matrix

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2] # to fetch 1st and 3rd matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,] # to fetch the 2nd row of the 1st matrix

array([3, 4, 5])

In [ ]:
a3[1,:,1] # to fetch 2nd column of 2nd matrix

array([10, 13, 16])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):  # it converts the 3D array into 1D
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T  # both does transpose, just different syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel (converts any dimensioanl vector to 1D array)
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking (basically adding same dimensional arrays horizontally)
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking (adding same dimensional arrays vertically)
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting (opposite of horizontal stacking)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting (opposite of vertical stacking)

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]