### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
np.random.seed(42)
a = np.random.randint(1,100,15)
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
np.random.seed(42)
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [ ]:
np.sort(a)

array([ 3, 15, 21, 22, 24, 52, 53, 61, 72, 75, 75, 83, 87, 88, 93])

In [ ]:
np.sort(b)

array([[15, 52, 72, 93],
       [21, 61, 83, 87],
       [24, 75, 75, 88],
       [ 2,  3, 22, 53],
       [ 2, 30, 38, 88],
       [21, 33, 60, 64]])

In [ ]:
np.sort(b,axis=0) # column wise sorting

array([[ 3, 21, 15,  2],
       [52, 22, 21,  2],
       [61, 30, 38, 24],
       [64, 60, 53, 33],
       [75, 75, 83, 72],
       [88, 93, 88, 87]])

In [ ]:
np.sort(a)[::-1] # To sort in reverse order

array([93, 88, 87, 83, 75, 75, 72, 61, 53, 52, 24, 22, 21, 15,  3])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
np.append(a,200)

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88,  24,   3,
        22,  53, 200])

In [ ]:
b

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[52., 93., 15., 72.,  1.],
       [61., 21., 83., 87.,  1.],
       [75., 75., 88., 24.,  1.],
       [ 3., 22., 53.,  2.,  1.],
       [88., 30., 38.,  2.,  1.],
       [64., 60., 21., 33.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[52.        , 93.        , 15.        , 72.        ,  0.30424224],
       [61.        , 21.        , 83.        , 87.        ,  0.52475643],
       [75.        , 75.        , 88.        , 24.        ,  0.43194502],
       [ 3.        , 22.        , 53.        ,  2.        ,  0.29122914],
       [88.        , 30.        , 38.        ,  2.        ,  0.61185289],
       [64.        , 60.        , 21.        , 33.        ,  0.13949386]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis. (Similar to horizontal stacking and vertical stacking)

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
np.expand_dims(a,axis=0)

array([[52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53]])

In [ ]:
np.expand_dims(a,axis=1)

array([[52],
       [93],
       [15],
       [72],
       [61],
       [21],
       [83],
       [87],
       [75],
       [75],
       [88],
       [24],
       [ 3],
       [22],
       [53]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
# np.where(condition,true,flase)
np.where(a>50,0,a)

array([ 0,  0, 15,  0,  0, 21,  0,  0,  0,  0,  0, 24,  3, 22,  0])

In [ ]:
# let replace all the even numbers with zero
np.where(a%2 == 0,0,a)

array([ 0, 93, 15,  0, 61, 21, 83, 87, 75, 75,  0,  0,  3,  0, 53])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
print(np.argmax(a))

1


In [ ]:
b

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [ ]:
np.argmax(b,axis=0) # axis=0-->column wise(to remember downwards)

array([4, 0, 2, 1])

In [ ]:
np.argmax(b,axis=1) # axis=1-->row wise(to remember sideways)

array([1, 3, 2, 2, 0, 0])

In [ ]:
# np.argmin
print(np.argmin(a))

12


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a) # cumsum--> cumulative sum

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 52, 145, 160, 232],
       [ 61,  82, 165, 252],
       [ 75, 150, 238, 262],
       [  3,  25,  78,  80],
       [ 88, 118, 156, 158],
       [ 64, 124, 145, 178]])

In [ ]:
np.cumsum(b,axis=0)

array([[ 52,  93,  15,  72],
       [113, 114,  98, 159],
       [188, 189, 186, 183],
       [191, 211, 239, 185],
       [279, 241, 277, 187],
       [343, 301, 298, 220]])

In [ ]:
np.cumsum(b)

array([  52,  145,  160,  232,  293,  314,  397,  484,  559,  634,  722,
        746,  749,  771,  824,  826,  914,  944,  982,  984, 1048, 1108,
       1129, 1162])

In [ ]:
# np.cumprod #cumulative product
np.cumprod(a)

array([                  52,                 4836,                72540,
                    5222880,            318595680,           6690509280,
               555312270240,       48312167510880,     3623412563316000,
         271755942248700000,  5467778844176048384,  2099483744258299904,
        6298451232774899712, -9008025468628619264,  2189996079131521024])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
print(np.percentile(a,100))

93.0


In [ ]:
print(np.percentile(a,0))

3.0


In [ ]:
print(np.percentile(a,50))

61.0


In [ ]:
print(np.median(a))

61.0


### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.histogram(a,bins=[0,20,40,80,100])

(array([2, 3, 6, 4]), array([  0,  20,  40,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [ ]:
# salary  ||   experience
# salary  ||  experience
# from this table we get the above result
# here 1st and 4th elt 1 means correlation between salary and salary, 2nd and 3rd elt 0.25 means correlation between salary and experience
# As here was 2 quantities so we got 2x2 matrix. if there were 3 quantities there would be 3x3 matrix.

### np.isin
numpy.isin() is used to check whether each element of one NumPy array is present in another array.
It returns a Boolean array of the same shape as the first array, where each value is True if the element exists in the second array, and False otherwise.
The two arrays can be of different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
items = [10,20,15,40,50,60,70,88,90,100]

np.isin(a,items)

array([False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [ ]:
a[np.isin(a,items)]

array([15, 88])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
b

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [ ]:
np.flip(b,axis=0)

array([[64, 60, 21, 33],
       [88, 30, 38,  2],
       [ 3, 22, 53,  2],
       [75, 75, 88, 24],
       [61, 21, 83, 87],
       [52, 93, 15, 72]])

In [ ]:
np.flip(b,axis=1)

array([[72, 15, 93, 52],
       [87, 83, 21, 61],
       [24, 88, 75, 75],
       [ 2, 53, 22,  3],
       [ 2, 38, 30, 88],
       [33, 21, 60, 64]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53])

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  15,  72,  61,  21,  83,  87,  75,  75,  88,  24,   3,
        22,  53])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,9)

array([110, 530,  15,  72,  61,  21,  83,  87,  75,  88,  24,   3,  22,
        53])

In [ ]:
np.delete(a,[0,2,4])

array([530,  72,  21,  83,  87,  75,  75,  88,  24,   3,  22,  53])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m) # those elts which are in n, but not in m

array([6, 7])

In [ ]:
np.setxor1d(m,n) # excludes all common elts

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,1)

/tmp/ipython-input-1810059527.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [ ]:
print(m[np.in1d(m,1)])

[1]


/tmp/ipython-input-3243102871.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(m[np.in1d(m,1)])


### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals